version: 0.2

phases:
  pre_build:
    commands:
      - gradle clean 
      - gradle build -x test
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region use-east-2 --no-include-email)
      - REPOSITORY_URI=634872338566.dkr.ecr.us-east-2.amazonaws.com/voyage-demo-registry
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:1.0 .
      - docker tag $REPOSITORY_URI:1.0 $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:1.0
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"discovery-server","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - build/libs/discovery-server.jar

