version: "3.8"

services:
  discovery-server:
    image: discovery-server
    container_name: discovery-server
    ports:
    - 8070:8070
    restart: on-failure
    networks:
      - voyage-service-network
    
networks:
   voyage-service-network:
  
  