eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'